spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/msorder
    driver-class-name: org.postgresql.Driver
    username: order
    password: 200125
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
